# Generated by Django 5.1.7 on 2025-04-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_question_answer_question_topic_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(related_name='questions', to='users.topic'),
        ),
    ]
